apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

configMapGenerator:
- files:
  - files/uwl_metrics_list.yaml
  name: observability-metrics-custom-allowlist
  options:
    disableNameSuffixHash: true
