apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: aiedge-e2e
spec:
  params:
  - name: model-name
    type: string
    description: Name of the directory where the model files are stored
  - default: "1"
    name: model-version
    type: string
    description: Version of the model
  - name: s3-bucket-name
    type: string
    description: "[S3 ONLY] S3 bucket name where the model is stored"
    default: ""
  - name: git-containerfile-repo
    type: string
    description: Git repository where the Containerfile is stored
  - name: git-containerfile-revision
    type: string
    description: Git revision to checkout when cloning the repository with the Containerfile
    default: "main"
  - name: containerfileRelativePath
    type: string
    description: Path to the Containerfile in the git repository for model server imagebuild
  - name: modelRelativePath
    type: string
    description: "Location of the model within the context of the source location.  Leave blank if the model files are at the root of the source location."
  - name: model-dir
    type: string
    description: Directory below <modelRelativePath>/<model-name>/ to be used as MODEL_DIR in image build.
    default: "."
  - name: fetch-model
    type: string
    description: "Fetch the model from Git or S3. Valid values in [s3, git]"
  - name: git-model-repo
    type: string
    description: The git repo url where the model files are stored
    default: ""
  - name: git-model-revision
    type: string
    description: The Git ref to use when cloning the git repo with the saved model
    default: "main"
  - name: test-endpoint
    type: string
    description: The inferencing endpoint for the model to use for testing
  - default: $(context.pipelineRun.namespace)
    name: target-namespace
    type: string
  - name: candidate-image-tag-reference
    type: string
    description: "A fully qualified image tag reference to be used for the candidate image build. E.g. registry.example.com/my-org/ai-model:1.0-1-candidate"
    default: image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.model-name):$(params.model-version)-candidate
  - name: target-image-tag-references
    type: array
    description: "An array of fully qualified image tag references to be used for the final image push. E.g. registry.example.com/my-org/ai-model:1.0-1"
  - name: gitops-git-server
  - name: gitops-git-api-server
  - name: gitops-git-org-name
  - name: gitops-git-repo-name
  - name: gitops-git-repo-branch-base
  - name: gitops-git-api-prefix
  - name: gitops-git-token-secret-name
  - name: gitops-git-token-secret-key
  - name: gitops-yq-script
  - name: upon-end
    type: string
    description: "Action to perform on the k8s deployment created to test the model container image. Valid values in [delete, keep, stop]"
    default: delete
  results:
  - name: s3-model-fetched-url
    description: The S3 URL used to download the model
    value: $(tasks.fetch-model-s3.results.s3-url)
  - name: git-model-fetched-commit
    description: The commit hash of the git repo where the model files were fetched from
    value: $(tasks.fetch-model-git.results.commit)
  - name: git-model-fetched-url
    description: The url of the git repo where the model files were fetched from
    value: $(tasks.fetch-model-git.results.url)
  - name: git-model-fetched-commit-epoch
    description: The commit timestamp of the git repo where the model files were fetched from
    value: $(tasks.fetch-model-git.results.committer-date)
  - name: git-containerfile-fetched-commit
    description: The commit hash of the git repo where the containerfile was fetched from
    value: $(tasks.git-clone-containerfile-repo.results.commit)
  - name: git-containerfile-fetched-url
    description: The url of the git repo where the containerfile was fetched from
    value: $(tasks.git-clone-containerfile-repo.results.url)
  - name: git-containerfile-fetched-commit-epoch
    description: The commit timestamp of the git repo where the containerfile was fetched from
    value: $(tasks.git-clone-containerfile-repo.results.committer-date)
  - name: model-files-size
    description: The size of the model files
    value: $(tasks.check-model-and-containerfile-exists.results.model-files-size)
  - name: model-files-list
    description: The list of model files
    value: $(tasks.check-model-and-containerfile-exists.results.model-files-list)
  - name: candidate-image-tag-reference
    description: The tag where the candidate model container image was pushed to
    value: $(tasks.build-container-image.results.IMAGE_URL)
  - name: target-image-tag-references
    description: The fully qualified image reference that the image was pushed to (e.g. registry.example.com/my-org/ai-model:1.0-1)
    value: $(tasks.retrieve-build-image-info.results.target-image-tag-references)
  - name: image-digest-reference
    description: The fully qualified image digest reference of the image
    value: $(tasks.retrieve-build-image-info.results.image-digest-reference)
  - name: image-size-bytes
    description: The size of the model container image in bytes
    value: $(tasks.retrieve-build-image-info.results.image-size-bytes)
  - name: buildah-sha
    description: The SHA digest of the model container image
    value: $(tasks.build-container-image.results.IMAGE_DIGEST)
  - name: model-name
    description: The model name
    value: $(tasks.retrieve-build-image-info.results.model-name)
  - name: model-version
    description: The model version
    value: $(tasks.retrieve-build-image-info.results.model-version)
  - name: image-creation-time
    description: The date and time the image was created at
    value: $(tasks.retrieve-build-image-info.results.image-creation-time)
  - name: buildah-version
    description: The buildah version used to build the model container image
    value: $(tasks.retrieve-build-image-info.results.buildah-version)
  - name: pr-url
    description: The URL of the pull request
    value: $(tasks.open-pr.results.URL)
  tasks:
  - name: fetch-model-git
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.git-model-repo)
    - name: revision
      value: $(params.git-model-revision)
    - name: subdirectory
      value: /model_dir-$(params.model-name)/
    workspaces:
    - name: output
      workspace: build-workspace-pv
    - name: ssl-ca-directory
      workspace: git-ssl-cert
    when:
    - input: "$(params.fetch-model)"
      operator: in
      values: ["git"]
  # Use kserve-download-model container image to fetch from S3 storage
  - name: fetch-model-s3
    params:
    - name: model-name
      value: $(params.model-name)
    - name: current-namespace
      value: $(context.pipelineRun.namespace)
    - name: s3-bucket-name
      value: $(params.s3-bucket-name)
    taskRef:
      kind: Task
      name: kserve-download-model
    workspaces:
    - name: workspace
      workspace: build-workspace-pv
    - name: s3-secret
      workspace: s3-secret
    - name: ssl-ca-directory
      workspace: s3-ssl-cert
    when:
    - input: "$(params.fetch-model)"
      operator: in
      values: ["s3"]
  - name: git-clone-containerfile-repo
    params:
    - name: url
      value: $(params.git-containerfile-repo)
    - name: revision
      value: $(params.git-containerfile-revision)
    - name: subdirectory
      value: /containerfile_repo/
    runAfter:
    - fetch-model-s3
    - fetch-model-git
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: build-workspace-pv
    - name: basic-auth
      workspace: git-basic-auth
    - name: ssl-ca-directory
      workspace: git-ssl-cert
  - name: check-model-and-containerfile-exists
    params:
    - name: model-name
      value: $(params.model-name)
    - name: modelRelativePath
      value: $(params.modelRelativePath)
    - name: containerfilePath
      value: containerfile_repo/$(params.containerfileRelativePath)
    - name: current-namespace
      value: $(context.pipelineRun.namespace)
    runAfter:
    - git-clone-containerfile-repo
    taskRef:
      kind: Task
      name: check-model-and-containerfile-exists
    workspaces:
    - name: workspace
      workspace: build-workspace-pv
  - name: build-container-image
    params:
    - name: IMAGE
      value: $(params.candidate-image-tag-reference)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/ubi9/buildah:latest
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: containerfile_repo/$(params.containerfileRelativePath)
    - name: CONTEXT
      value: model_dir-$(params.model-name)/$(params.modelRelativePath)/$(params.model-name)
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: "--build-arg MODEL_NAME=$(params.model-name) --build-arg MODEL_DIR=$(params.model-dir)"
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - check-model-and-containerfile-exists
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: build-workspace-pv
  - name: test-container-deploy
    params:
    - name: SCRIPT
      value: |
        cat <<EOF | oc apply -f -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          creationTimestamp: null
          labels:
            app: $(params.model-name)-$(params.model-version)
            model-name: $(params.model-name)
          name: $(params.model-name)-$(params.model-version)
          namespace: $(params.target-namespace)
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: $(params.model-name)-$(params.model-version)
          strategy: {}
          template:
            metadata:
              creationTimestamp: null
              labels:
                app: $(params.model-name)-$(params.model-version)
            spec:
              containers:
              - image: $(params.candidate-image-tag-reference)
                name: $(params.model-name)-$(params.model-version)
                livenessProbe:
                  failureThreshold: 10
                  httpGet:
                    path: /v2/health/live
                    port: 8080
                    scheme: HTTP
                  periodSeconds: 5
                  successThreshold: 1
                readinessProbe:
                  failureThreshold: 10
                  httpGet:
                    path: /v2/models/$(params.model-name)/ready
                    port: 8080
                    scheme: HTTP
                  periodSeconds: 5
                  successThreshold: 1
                ports:
                - containerPort: 8080
                resources: {}
        status: {}
        EOF
        oc wait deployment -n $(params.target-namespace) $(params.model-name)-$(params.model-version) --for condition=Available=True --timeout=120s
        oc wait pod -n $(params.target-namespace) -l app=$(params.model-name)-$(params.model-version) --for condition=Ready=True --timeout=120s
    taskRef:
      kind: ClusterTask
      name: openshift-client
    runAfter:
      - build-container-image
  - name: create-default-service
    params:
    - name: SCRIPT
      value: oc expose deployment  $(params.model-name)-$(params.model-version) --port=8080
        --target-port=8080 --selector='app=$(params.model-name)-$(params.model-version)'
        --dry-run=client -o yaml |  oc apply -f -
    - name: VERSION
      value: latest
    runAfter:
    - test-container-deploy
    taskRef:
      kind: ClusterTask
      name: openshift-client
  - name: test-model-rest-svc
    params:
    - name: model-name
      value: $(params.model-name)
    - name: model-version
      value: $(params.model-version)
    - name: test-endpoint
      value: $(params.test-endpoint)
    runAfter:
    - create-default-service
    taskRef:
      kind: Task
      name: test-model-rest-svc
    workspaces:
    - name: test-data
      workspace: test-data
  - name: stop-deployment
    params:
    - name: SCRIPT
      value: |
        if [ "$(params.upon-end)" == "stop" ]; then
          oc scale deployment.apps/$(params.model-name)-$(params.model-version) --replicas=0
        elif [ "$(params.upon-end)" == "delete" ]; then
          oc delete all --selector=app=$(params.model-name)-$(params.model-version)
        elif [ "$(params.upon-end)" == "keep" ]; then
          echo "Keeping the deployment running."
        else
          echo "Invalid value for upon-end parameter."
          exit 1
        fi
    - name: VERSION
      value: latest
    runAfter:
    - test-model-rest-svc
    taskRef:
      kind: ClusterTask
      name: openshift-client
  - name: retrieve-build-image-info
    taskRef:
      kind: Task
      name: retrieve-build-image-info
    params:
    - name: model-name
      value: $(params.model-name)
    - name: model-version
      value: $(params.model-version)
    - name: namespace
      value: $(params.target-namespace)
    - name: buildah-sha
      value: $(tasks.build-container-image.results.IMAGE_DIGEST)
    - name: pipeline-run-uid
      value: $(context.pipelineRun.uid)
    - name: candidate-image-tag-reference
      value: $(params.candidate-image-tag-reference)
    - name: target-image-tag-references
      value: ["$(params.target-image-tag-references[*])"]
    runAfter:
    - test-model-rest-svc
    - stop-deployment
    workspaces:
    - name: images-url
      workspace: build-workspace-pv
  - name: skopeo-copy
    params:
    - name: srcTLSverify
      value: "true"
    - name: destTLSverify
      value: "true"
    runAfter:
    - retrieve-build-image-info
    taskRef:
      kind: ClusterTask
      name: skopeo-copy
    workspaces:
    - name: images-url
      workspace: build-workspace-pv

  - name: gitops-git-clone
    params:
      - name: url
        value: $(params.gitops-git-server)/$(params.gitops-git-org-name)/$(params.gitops-git-repo-name)
      - name: revision
        value: $(params.gitops-git-repo-branch-base)
      - name: gitInitImage
        value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:1a50511583fc02a27012d17d942e247813404104ddd282d7e26f99765174392c
      - name: subdirectory
        value: /$(params.gitops-git-repo-name)/
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
      - name: output
        workspace: build-workspace-pv
      - name: basic-auth
        workspace: git-basic-auth
  - name: yq-update
    params:
      - name: SCRIPT
        value: $(params.gitops-yq-script)
      - name: env-image-name
        value: $(tasks.retrieve-build-image-info.results.first-image-registry-repo)
      - name: env-image-digest
        value: $(tasks.build-container-image.results.IMAGE_DIGEST)
      - name: git-repo-path
        value: $(params.gitops-git-repo-name)
    runAfter:
      - gitops-git-clone
      - retrieve-build-image-info
    taskRef:
      kind: Task
      name: yq-update
    workspaces:
      - name: source
        workspace: build-workspace-pv
  - name: gitops-commit-and-push
    params:
      - name: BASE_IMAGE
        value: cgr.dev/chainguard/git:root-2.39@sha256:7759f87050dd8bacabe61354d75ccd7f864d6b6f8ec42697db7159eccd491139
      - name: GIT_USER_NAME
        value: Pipeline Image Updater
      - name: GIT_USER_EMAIL
        value: pipeline@example.com
      - name: GIT_SCRIPT
        value: |
          # Move repo to HOME so Git does not complain
          # https://stackoverflow.com/a/71941707/19020549
          cp -r $(workspaces.source.path)/$(params.gitops-git-repo-name) ~/$(params.gitops-git-repo-name)

          cd ~/$(params.gitops-git-repo-name)

          PR_BRANCH=pipeline_$(context.pipelineRun.uid)
          git checkout -b $PR_BRANCH

          if [ -z "$(git status --porcelain)" ]; then
              echo "Update did not cause a modification"
              exit 0
          fi

          git commit -am "Update image ref from pipeline"
          git push origin $PR_BRANCH:$PR_BRANCH
      - name: USER_HOME
        value: /home/git
      - name: VERBOSE
        value: "true"
    runAfter:
      - yq-update
      - skopeo-copy
    taskRef:
      kind: ClusterTask
      name: git-cli
    workspaces:
      - name: source
        workspace: build-workspace-pv
      - name: basic-auth
        workspace: git-basic-auth
  - name: open-pr
    params:
      - name: GITHUB_HOST_URL
        value: $(params.gitops-git-api-server)
      - name: API_PATH_PREFIX
        value: $(params.gitops-git-api-prefix)
      - name: REPO_FULL_NAME
        value: $(params.gitops-git-org-name)/$(params.gitops-git-repo-name)
      - name: GITHUB_TOKEN_SECRET_NAME
        value: $(params.gitops-git-token-secret-name)
      - name: GITHUB_TOKEN_SECRET_KEY
        value: $(params.gitops-git-token-secret-key)
      - name: AUTH_TYPE
        value: Bearer
      - name: HEAD
        value: pipeline_$(context.pipelineRun.uid)
      - name: BASE
        value: $(params.gitops-git-repo-branch-base)
      - name: BODY
        value: |
          This pull request has been automatically generated by an OpenShift Pipeline in order to update an image ref. Here are the details:

          | Key              | Value                                                                     |
          |------------------|---------------------------------------------------------------------------|
          | Pipeline Name    | $(context.pipeline.name)                                                  |
          | PipelineRun Name | $(context.pipelineRun.name)                                               |
          | PipelinRun UID   | `$(context.pipelineRun.uid)`                                              |
          | Image registry   | `$(tasks.retrieve-build-image-info.results.first-image-registry-repo)`    |
          | New Digest       | `$(tasks.build-container-image.results.IMAGE_DIGEST)`                     |
      - name: TITLE
        value: "Auto: update image ref"
    runAfter:
      - gitops-commit-and-push
    taskRef:
      kind: Task
      name: github-open-pr
    when:
      - input: $(tasks.gitops-git-clone.results.commit)
        operator: notin
        values:
          - $(tasks.gitops-commit-and-push.results.commit)
  workspaces:
  - name: build-workspace-pv
  - name: s3-secret
  - name: git-basic-auth
    optional: true
  - name: test-data
  - name: git-ssl-cert
    optional: true
  - name: s3-ssl-cert
    optional: true
