apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: aiedge-e2e
  generateName: aiedge-e2e-
spec:
  params:
  - name: model-name
    value: tensorflow-housing
  - name: model-version
    value: "1"
  - name: s3-bucket-name
    value: rhoai-edge-models
  - name: gitServer
    value: https://github.com
  - name: gitOrgName
    value: opendatahub-io
  - name: gitRepoName
    value: ai-edge
  - name: containerfileRelativePath
    value: pipelines/containerfiles/Containerfile.openvino.mlserver.mlflow
  - name: fetch-model
    value: "git"
  - name: git-model-repo
    value: https://github.com/opendatahub-io/ai-edge.git
  - name: modelRelativePath
    value: pipelines/models
  - name: model-dir
    value: "tf2model"
  - name: git-revision
    value: "main"
  - name: test-endpoint
    value: "v1/models/tensorflow-housing/versions/1:predict"
  - name: target-imagerepo
    value: rhoai-edge
  pipelineRef:
    name: aiedge-e2e
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
  - name: buildah-cache
    # Have the tekton controller allocate a PVC for each pipeline run that persists for the life of each PipelineRun object.
    # NOTE: This PVC will be deleted by the Tekton controller when the PipelineRun is deleted
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: s3-secret
    secret:
        secretName: credentials-s3
  - emptyDir: {}
    name: workspace
  - configMap:
      name: tensorflow-housing-test-data
    name: test-data
