---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: application
  namespace: near-edge-acm-template
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - near-edge-acm-template
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: channel
  namespace: near-edge-acm-template
spec:
  type: Git
  pathname: 'https://github.com/opendatahub-io/ai-edge'
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: near-edge-acm-template
  name: placement
  namespace: near-edge-acm-template
spec:
  clusterSets:
    - poc-near-edge
  predicates:
    - requiredClusterSelector:
        labelSelector: {}
  tolerations:
    - key: cluster.open-cluster-management.io/unreachable
      operator: Exists
    - key: cluster.open-cluster-management.io/unavailable
      operator: Exists
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: acm/odh-edge/apps/app
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: near-edge-acm-template
  name: subscription
  namespace: bike-rental-app
spec:
  channel: channel
  placement:
    placementRef:
      kind: Placement
      name: placement
