kind: Deployment
apiVersion: apps/v1
metadata:
  name: MODEL_NAME-MODEL_VERSION # CHANGE THIS
  labels:
    app: MODEL_NAME-MODEL_VERSION # CHANGE THIS
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MODEL_NAME-MODEL_VERSION # CHANGE THIS
  template:
    metadata:
      labels:
        app: MODEL_NAME-MODEL_VERSION # CHANGE THIS
    spec:
      containers:
      - readinessProbe:
          httpGet:
            path: /v2/models/MODEL_NAME/ready # CHANGE THIS
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 8
        terminationMessagePath: /dev/termination-log
        name: model-version
        livenessProbe:
          httpGet:
            path: /v2/health/live
            port: 8080
            scheme: HTTP
          timeoutSeconds: 1
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 8
        ports:
        - containerPort: 8080
          protocol: TCP
        imagePullPolicy: IfNotPresent
        terminationMessagePolicy: File
        image: MODEL_IMAGE # CHANGE THIS
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
