kind: Service
apiVersion: v1
metadata:
  name: MODEL_NAME-MODEL_VERSION # CHANGE THIS
  labels:
    app: MODEL_NAME-MODEL_VERSION # CHANGE THIS
spec:
  selector:
    app: MODEL_NAME-MODEL_VERSION # CHANGE THIS
  ports:
  - name: rest
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: seldon-metrics
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: grpc
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: ClusterIP
