{
 "title": "Inference metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum{cluster=\"$cluster\",namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}} {{path}} __ {{method}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "namespace:container_memory_usage_bytes:sum{cluster=\"$cluster\",namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "OVMS Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ovms_requests_success{cluster=~\"$cluster\"}) by(namespace)",
     "legendFormat": "{{namespace}} success"
    },
    {
     "expr": "sum(ovms_requests_fail{cluster=~\"$cluster\"}) by(namespace)",
     "legendFormat": "{{namespace}} fail"
    }
   ]
  },
  {
   "title": "Inference Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(rest_server_requests_total{cluster=~\"$cluster\"}[$__rate_interval]) * 60) by(namespace, path, method)",
     "legendFormat": "{{namespace}} {{path}} __ {{method}}"
    }
   ]
  }
 ]
}