apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    tekton.dev/pipeline: test-mlflow-image
  generateName: test-mlflow-image-bike-rentals-
spec:
  params:
  - name: model-name
    value: bike-rentals-auto-ml
  - name: model-version
    value: "1"
  - name: test-endpoint
    value: "invocations"
  - name: target-namespace
    value: $(context.pipelineRun.namespace)
  - name: target-imagerepo
    value: rhoai-edge
  pipelineRef:
    name: test-mlflow-image
  serviceAccountName: pipeline
  podTemplate:
    env:
    - name: MODEL_DEPLOY_CM
      valueFrom:
        configMapKeyRef:
          name: model-deployment
          key: model-deployment.yaml
    - name: MODEL_SERVICE_CM
      valueFrom:
        configMapKeyRef:
          name: model-service
          key: model-service.yaml
  timeout: 1h0m0s
  workspaces:
  - emptyDir: {}
    name: workspace
  - configMap:
      name: bike-rentals-test-data
    name: test-data
