apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-mlflow-image
spec:
  params:
  - name: model-name
    type: string
  - default: "1"
    name: model-version
    type: string
  - name: test-endpoint
    type: string
  - default: $(context.pipelineRun.namespace)
    name: target-namespace
    type: string
  - name: target-imagerepo
    type: string
  tasks:
  - name: deploy-container
    params:
    - name: SCRIPT
      value: |
        echo "$MODEL_DEPLOY_CM" | sed 's/MODEL_NAME/$(params.model-name)/g; s/MODEL_VERSION/$(params.model-version)/g; s/MODEL_IMAGE/$(params.model-name):$(params.model-version)/g' | oc apply -f -
        oc wait deployment -n $(params.target-namespace) $(params.model-name)-$(params.model-version) --for condition=Available=True --timeout=120s
        oc wait pod -n $(params.target-namespace) -l app=$(params.model-name)-$(params.model-version) --for condition=Ready=True --timeout=120s
    taskRef:
      kind: ClusterTask
      name: openshift-client
  - name: create-service
    params:
    - name: SCRIPT
      value: |
        echo "$MODEL_SERVICE_CM" | sed 's/MODEL_NAME/$(params.model-name)/g; s/MODEL_VERSION/$(params.model-version)/g' | oc apply -f -
    - name: VERSION
      value: latest
    runAfter:
    - deploy-container
    taskRef:
      kind: ClusterTask
      name: openshift-client
  - name: test-mlflow-rest-svc
    params:
    - name: model-name
      value: $(params.model-name)
    - name: model-version
      value: $(params.model-version)
    - name: test-endpoint
      value: $(params.test-endpoint)
    runAfter:
    - create-service
    taskRef:
      kind: Task
      name: test-mlflow-rest-svc
    workspaces:
    - name: test-data
      workspace: test-data
  - name: skopeo-copy
    params:
    - name: srcImageURL
      value: docker://image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/$(params.model-name):$(params.model-version)
    - name: destImageURL
      value: docker://quay.io/$(params.target-imagerepo)/$(params.model-name):$(params.model-version)
    - name: srcTLSverify
      value: "true"
    - name: destTLSverify
      value: "true"
    runAfter:
    - test-mlflow-rest-svc
    taskRef:
      kind: ClusterTask
      name: skopeo-copy
    workspaces:
    - name: images-url
      workspace: workspace
  workspaces:
  - name: workspace
  - name: test-data
